# Generated by Django 3.2.3 on 2021-05-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.DecimalField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], decimal_places=2, max_digits=15),
        ),
    ]
